"""Makes title as primary key and cascade relation table

Revision ID: b1f07eb47154
Revises: dc15a018c241
Create Date: 2020-06-13 17:20:20.291505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1f07eb47154'
down_revision = 'dc15a018c241'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ratings_movie_snapshot_id_fkey', 'ratings', type_='foreignkey')
    op.drop_column('movie_snapshots', 'id')
    op.execute('alter table movie_snapshots add primary key(title)')
    op.add_column('ratings', sa.Column('movie_snapshot_title', sa.String(), nullable=False))
    op.create_foreign_key('ratings_movie_snapshot_title_fkey', 'ratings', 'movie_snapshots', ['movie_snapshot_title'], ['title'])
    op.drop_column('ratings', 'movie_snapshot_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ratings_movie_snapshot_title_fkey', 'ratings', type_='foreignkey')
    op.drop_column('ratings', 'movie_snapshot_title')
    op.add_column('movie_snapshots', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint('movie_snapshots_pkey', 'movie_snapshots', type_='primary')
    op.execute('alter table movie_snapshots add primary key(id)')
    op.add_column('ratings', sa.Column('movie_snapshot_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('ratings_movie_snapshot_id_fkey', 'ratings', 'movie_snapshots', ['movie_snapshot_id'], ['id'])
    # ### end Alembic commands ###
